global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "vertex-app"
    scrape_interval: 5s
    static_configs:
      - targets: ["vertex-app:5000"]
        labels:
          service: "vertex-app"
          environment: "production"
    metrics_path: /metrics

  - job_name: "analytics"
    scrape_interval: 15s
    static_configs:
      - targets: ["analytics:8100"]
        labels:
          service: "analytics"
          environment: "production"
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
